apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: platform-assignment
data:
  KAFKA_BROKER: kafka-service:9092
  KAFKA_TOPIC: counter-events
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
